# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8ac3bc9d91f7e092243df2c9c468cf9e4f0254300f33d17ac9850ce4cdbb9e8ee7f5452e6f0d8fead77d23edf379b02fcea2f5f0948b7bb12e4236f7be49ed2

test:
  secret_key_base: 249aa9bf043b3a5d6fde2b6d7e6872ac4d0495945ad56a59c40d4ce828200865ac28ccb24bb26d5ec9960feafc136b881ff802a88dba7bd16c3610071fc388d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
